name: Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,bugfix'
          ignore: main,dev
          min_length: 5
          max_length: 20

      - uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json

      - uses: actions/checkout@v6

      - name: Run swiftlint
        run: fastlane lint

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: cache
          key: ${{ runner.os }}-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-packages-

      - name: Set IgnoreFileSystemDeviceInodeChanges flag
        run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES

      - name: Run Tests (No Cache)
        if: steps.packages-cache.outputs.cache-hit != 'true'
        run: fastlane tests clone_source_packages:true

      - name: Run Tests (Cache)
        if: steps.packages-cache.outputs.cache-hit == 'true'
        run: fastlane tests clone_source_packages:true skip_package_dependencies_resolution:true disable_package_automatic_updates:true skip_build:true
