name: Assert Branch Naming Convention
on: create

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '([a-z])+\/([a-z])+'
          allowed_prefixes: 'feature,bugfix'
          ignore: main,dev
          min_length: 5
          max_length: 20
