name: Pull Request

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Cache packages
        uses: actions/cache@v3
        id: packages-cache
        with:
          path: cache
          key: ${{ runner.os }}-packages-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-packages-

      - name: Run Tests (No Cache)
        if: steps.packages-cache.outputs.cache-hit != 'true'
        run: fastlane tests clone_source_packages:true

      - name: Run Tests (Cache)
        if: steps.packages-cache.outputs.cache-hit == 'true'
        run: fastlane tests clone_source_packages:true skip_package_dependencies_resolution:true disable_package_automatic_updates:true skip_build:true
